// ------------------------------------------------------------------------ //
// Copyright 2021 SPTK Working Group                                        //
//                                                                          //
// Licensed under the Apache License, Version 2.0 (the "License");          //
// you may not use this file except in compliance with the License.         //
// You may obtain a copy of the License at                                  //
//                                                                          //
//     http://www.apache.org/licenses/LICENSE-2.0                           //
//                                                                          //
// Unless required by applicable law or agreed to in writing, software      //
// distributed under the License is distributed on an "AS IS" BASIS,        //
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. //
// See the License for the specific language governing permissions and      //
// limitations under the License.                                           //
// ------------------------------------------------------------------------ //

#ifndef SPTK_GENERATION_PERIODIC_WAVEFORM_GENERATION_H_
#define SPTK_GENERATION_PERIODIC_WAVEFORM_GENERATION_H_

#include "SPTK/input/input_source_interpolation_with_magic_number.h"
#include "SPTK/utils/sptk_utils.h"

namespace sptk {

/**
 * Generate periodic waveform from pitch value.
 *
 * The input is a sequence of pitch value which can be either a continuous value
 * or a magic number. The output is the periodic waveform generated by the input
 * sequence.
 */
class PeriodicWaveformGeneration {
 public:
  /**
   * @param[in] unvoiced_value Value on unvoiced region.
   * @param[in] strict If true, strictly drop sinusoidal in an unvoiced region.
   * @param[in] input_source Input source.
   */
  PeriodicWaveformGeneration(
      double unvoiced_value, bool strict,
      InputSourceInterpolationWithMagicNumber* input_source);

  virtual ~PeriodicWaveformGeneration() {
  }

  /**
   * @return True if this object is valid.
   */
  bool IsValid() const {
    return is_valid_;
  }

  /**
   * Get periodic waveform.
   *
   * @param[out] sin Sine waveform (optional).
   * @param[out] cos Cosine waveform (optional).
   * @param[out] sawtooth Sawtooth waveform (optional).
   * @param[out] pitch Pitch (optional).
   * @return True on success, false on failure.
   */
  bool Get(double* sin, double* cos, double* sawtooth, double* pitch);

 private:
  const double unvoiced_value_;
  const bool strict_;

  InputSourceInterpolationWithMagicNumber* input_source_;

  bool is_valid_;

  // Phase value ranging from 0 to 2 x pi
  double phase_;

  // For strict = false
  double voiced_pitch_;
  bool extending_;

  DISALLOW_COPY_AND_ASSIGN(PeriodicWaveformGeneration);
};

}  // namespace sptk

#endif  // SPTK_GENERATION_PERIODIC_WAVEFORM_GENERATION_H_
