name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install csh parallel valgrind libpcre3-dev ffmpeg

      - name: Tool
        run: cd tools && make check -j 4 PYTHON_VERSION=3

      - name: Make
        run: make debug

      - name: Format
        run: make format

      - name: Test
        run: make test

  windows-latest:
    runs-on: windows-latest

    steps:
      - name: Clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Make
        run: ./make.bat
