name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get install csh parallel valgrind
    - name: setup
      run: cd tools; make check -j 4 PYTHON_VERSION=3
    - name: make
      run: make debug
    - name: make format
      run: make format
    - name: make test
      run: make test
